name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/onesubmit
          
          # 1. Reset Kode
          git reset --hard
          git pull origin main
          
          # 2. Pastikan folder ada (Jaga-jaga)
          mkdir -p storage/framework/cache/data
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          
          # --- BAGIAN CHMOD DIHAPUS ---
          # Kita hapus perintah 'chmod' karena sudah dihandle oleh ACL di server.
          # Ini mencegah error "Operation not permitted".
          
          # 3. Standard Deployment
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          
          # 4. Clear Cache
          php artisan optimize:clear
          
          # 5. Link & Restart
          php artisan storage:link || true
          php artisan queue:restart