name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/onesubmit
          git reset --hard
          git pull origin main
          
          # 1. Pastikan folder cache SELALU ADA (Anti Error 500)
          mkdir -p storage/framework/cache/data
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          
          # 2. Pastikan izinnya TERBUKA (777) agar Laravel bisa nulis log
          chmod -R 777 storage
          
          # 3. Install Library & Update Database
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          
          # 4. Bersihkan Cache lama
          php artisan optimize:clear
          
          # 5. Link Storage (Pakai "|| true" agar tidak error kalau link sudah ada)
          php artisan storage:link || true
          
          # 6. Restart Worker
          php artisan queue:restart